name       : arx-libertatis
version    : 1.1.2.2
release    : 4
source     :
    - https://github.com/arx/ArxLibertatis/archive/1.1.2-r2.tar.gz : adcf960bf6ab27f5339d4ed54d38181816a2c215cc969c7a55cfe56212708cef
license    : GPL-3.0
component  : games.rpg
summary    : Cross-platform port of Arx Fatalis
description: |
    Cross-platform port of Arx Fatalis
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(openal)
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/cmake-3.5.patch
    %cmake -DCMAKE_INSTALL_LIBEXECDIR=%libdir%/%PKGNAME% .
build      : |
    %make
install    : |
    %make_install
