name       : arx-libertatis
version    : 1.2.1
release    : 8
source     :
    - https://github.com/arx/ArxLibertatis/archive/refs/tags/1.2.1.tar.gz : b55add66202c621491880cebf74601254d70a85d7281a16fbd8a935d675fa389
license    : GPL-3.0-or-later
component  : games.rpg
summary    : Cross-platform port of Arx Fatalis
description: |
    Cross-platform port of Arx Fatalis
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(epoxy)
    - pkgconfig(freetype2)
    - pkgconfig(glm)
    - pkgconfig(libcurl)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(x11)
    - imagemagick
    - inkscape
    - libboost-devel
    - optipng
setup      : |
    %cmake -DCMAKE_INSTALL_LIBEXECDIR=%libdir%/%PKGNAME% .
build      : |
    %make
install    : |
    %make_install
