name       : arx-libertatis
version    : 1.1.2.1
release    : 5
source     :
    - https://github.com/arx/ArxLibertatis/archive/1.1.2-r1.tar.gz : 985bf9795b8ba68f6cef55c9b308afc9bcbd95908a123396b13ed88bb6a40967
license    : GPL-3.0-or-later
component  : games.rpg
summary    : Cross-platform port of Arx Fatalis
description: |
    Cross-platform port of Arx Fatalis
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(openal)
    - pkgconfig(Qt5Core)
    - pkgconfig(sdl)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/arx-libertatis-1.1.2-build.patch
    %cmake -DCMAKE_INSTALL_LIBEXECDIR=%libdir%/%PKGNAME% .
build      : |
    %make
install    : |
    %make_install
